version: '2'
services:
  mtail:
    build: mtail
    command:
      - "-progs"
      - "/etc/mtail"
      - "-logs"
      - "/var/log/chia/debug.log"
      - "-logs"
      - "/var/log/plotter/*"
      - "-logtostderr"
    volumes:
      - /mnt/user/appdata/machinaris/mainnet/log/:/var/log/chia/
      - /mnt/user/appdata/machinaris/plotman/logs/:/var/log/plotter/
    network_mode: host