{
 "title": "Chia",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(node_filesystem_size_bytes, instance)"
    }
   },
   {
    "name": "mounts",
    "query": {
     "query": "label_values(node_filesystem_size_bytes, mountpoint)"
    }
   },
   {
    "name": "disks",
    "query": {
     "query": "label_values(node_disk_io_time_seconds_total, device)"
    }
   },
   {
    "name": "interfaces",
    "query": {
     "query": "label_values(node_network_receive_bytes_total, device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total Plots Passed the Filter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "chia_harvester_plots_eligible", "legendFormat": "Plots passed filter" },
    { "expr": "chia_harvester_plots_eligible", "legendFormat": "Plots passed filter mike" }
   ]
  },
  {
   "title": "Local Plots Passed the Filter",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "chia_harvester_plots_eligible", "legendFormat": "Local Plots" },
    { "legendFormat": "Salad Plots" }
   ]
  },
  {
   "title": "Proofs Found",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_harvester_proofs_total" }
   ]
  },
  {
   "title": "Total plots",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_harvester_plots_total", "legendFormat": "Salad Plots" },
    { "expr": "chia_harvester_plots_total", "legendFormat": "Local Plots" }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=\"$node\",device=~\"$disks\"}[$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Balance",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "mojo" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "chia_wallet_confirmed_balance_mojo"
    }
   ]
  },
  {
   "title": "Disk Thoughput",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_disk_read_bytes_total{instance=\"$node\",device=~\"$disks\"}[$__rate_interval])",
     "legendFormat": "{{device}} read"
    },
    {
     "expr": "irate(node_disk_written_bytes_total{instance=\"$node\",device=~\"$disks\"}[$__rate_interval])",
     "legendFormat": "{{device}} written"
    }
   ]
  },
  {
   "title": "Search Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(chia_harvester_search_time_bucket[$__rate_interval])) by (le,plots_eligible))",
     "legendFormat": "{{plots_eligible}} Plots Passed Filter"
    }
   ]
  },
  {
   "title": "Search Time Histogram (at least one plot passed filter)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(chia_harvester_search_time_bucket{plots_eligible!=\"0\"}[$__range])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(irate(node_cpu_seconds_total{mode!=\"idle\", instance=\"$node\"}[$__rate_interval])) by (mode)",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=\"$node\",mountpoint=~\"$mounts\"} - node_filesystem_avail_bytes{instance=\"$node\",mountpoint=~\"$mounts\"}) / node_filesystem_size_bytes{instance=\"$node\",mountpoint=~\"$mounts\"}",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "Plots",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_harvester_plots_total", "legendFormat": "Local Plots", "panelId": 35 },
    { "expr": "chia_harvester_plots_total", "legendFormat": "Salad Plots" }
   ]
  },
  {
   "title": "Local Plots",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_harvester_plots_total", "legendFormat": "Local Plots" }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"$node\"} - node_memory_MemFree_bytes{instance=\"$node\"} - node_memory_Buffers_bytes{instance=\"$node\"} - node_memory_Cached_bytes{instance=\"$node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"$node\"}",
     "legendFormat": "Buffered"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"$node\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"$node\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Network Usage (last 24hr)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(node_network_receive_bytes_total{instance=\"$node\",device=~\"$interfaces\"}[24h]))",
     "legendFormat": " rx"
    },
    {
     "expr": "sum(increase(node_network_transmit_bytes_total{instance=\"$node\",device=~\"$interfaces\"}[24h]))",
     "legendFormat": "tx"
    }
   ]
  },
  {
   "title": "Plotter Logs",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "{job=\"plotter\"}!=\"uniform sort\""
    }
   ]
  },
  {
   "title": "Harvester Warnings",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "{job=\"chia\"}|=\"harvester.harvester\"|=\"WARNING\""
    }
   ]
  },
  {
   "title": "Salad Plots",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "chia_harvester_plots_total", "legendFormat": "Salad Plots" }
   ]
  }
 ]
}